name: Bannerclone
version: '${project.version}'
main: bannerclone.bannerclone.Bannerclone
api-version: 1.18
description: This clones banners
commands:
  bannerCreate:
    description: saves a banner for crafting
    usage: /<command>
    permission: yourplugin.yourcommandpermission
