name: Bannerclone
version: '${project.version}'
main: bannerclone.bannerclone.Bannerclone
api-version: 1.18
description: This clones banners
commands:
  bannerCreate:
    description: Saves a banner for crafting
    usage: /<command>
    permission: yourplugin.yourcommandpermission
  bannerList:
    description: Lists saved banners
    usage: /<command>
    permission: yourplugin.yourcommandpermission